
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - 'c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface SitePreferences {
			/**
			* 
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#5) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#101)
			*/
			APIKEY: string | null;

			/**
			* 
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#12) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#100)
			*/
			APIBASE: string | null;

			/**
			* 
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#19) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#99)
			*/
			APITYPE: string | null;

			/**
			* 
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#26) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#102)
			*/
			APIVERSION: string | null;

			/**
			* 
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#33) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#98)
			*/
			CHATDEPLOYMENT: string | null;

			/**
			* 
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#40) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#97)
			*/
			EMBEDDINGDEPLOYMENT: string | null;

			/**
			* 
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#47) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#96)
			*/
			XSERVICELINE: string | null;

			/**
			* 
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#54) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#95)
			*/
			XBRAND: string | null;

			/**
			* 
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#61) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#94)
			*/
			XPROJECT: string | null;

			/**
			* CHATMODEL
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#68) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#93)
			*/
			CHATMODEL: string | null;

			/**
			* EMBEDDINGMODEL
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#75) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#93)
			*/
			CHATMODEL: string | null;

			/**
			* 
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#82) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#104)
			*/
			faqContentID: string | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
					/**
			* 
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#5) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#101)
			*/
			(name: 'APIKEY'): string | null;
			
			/**
			* 
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#12) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#100)
			*/
			(name: 'APIBASE'): string | null;
			
			/**
			* 
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#19) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#99)
			*/
			(name: 'APITYPE'): string | null;
			
			/**
			* 
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#26) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#102)
			*/
			(name: 'APIVERSION'): string | null;
			
			/**
			* 
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#33) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#98)
			*/
			(name: 'CHATDEPLOYMENT'): string | null;
			
			/**
			* 
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#40) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#97)
			*/
			(name: 'EMBEDDINGDEPLOYMENT'): string | null;
			
			/**
			* 
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#47) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#96)
			*/
			(name: 'XSERVICELINE'): string | null;
			
			/**
			* 
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#54) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#95)
			*/
			(name: 'XBRAND'): string | null;
			
			/**
			* 
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#61) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#94)
			*/
			(name: 'XPROJECT'): string | null;
			
			/**
			* CHATMODEL
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#68) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#93)
			*/
			(name: 'CHATMODEL'): string | null;
			
			/**
			* EMBEDDINGMODEL
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#75) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#93)
			*/
			(name: 'CHATMODEL'): string | null;
			
			/**
			* 
			* @group AZURE CREDENTIALS - AZURE CREDENTIALS
			* @source [attribute](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#82) | [group](file:c:\PERSONAL_WORKSPACE\SFCC_COMPONENTS\app_customer_assistant\siteData\build_sitedata\meta\system-objecttype-extensions.xml#104)
			*/
			(name: 'faqContentID'): string | null;
			
	}
}